"""Storage interface. Default impl is SQLite (single file, no external DB)."""

from __future__ import annotations

from typing import Protocol


class RoutineStore(Protocol):
    def list_routines(self, *, since: str | None = None, include_deleted: bool = False) -> list[dict]: ...
    def get_routine(self, address: str) -> dict | None: ...
    def put_routine(self, record: dict) -> None: ...
    def delete_routine(self, address: str, *, last_modified: str) -> dict | None: ...
    def archive_history(self, address: str, last_modified: str, payload: dict) -> None: ...


class TaskStore(Protocol):
    def list_tasks(
        self,
        *,
        since: str | None = None,
        source: str | None = None,
        include_deleted: bool = True,
    ) -> list[dict]: ...
    def get_task(self, task_id: str) -> dict | None: ...
    def find_by_external(self, source: str, external_id: str) -> dict | None: ...
    def put_task(self, record: dict) -> None: ...
    def delete_task(self, task_id: str, *, last_modified: str) -> dict | None: ...
    def purge_tombstones(self, *, older_than: str) -> int: ...
